service: AcademyOfCleaning

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
  stage: dev
  region: us-west-1

# you can add packaging information here
#package:
#  include:
#    - include-me-dir/**
#  exclude:
#    - exclude-me-dir/**

functions:
  hello:
    handler: handler.landing
    events:
      - http:
          path: /home
          method: any

  searchCandidates:
    handler: searchPage.applySearch
    events:
      - http:
          path: /search
          method: GET

#    Define function environment variables here
#    environment:
#      variable2: value2
